version: 2.0
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: 
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
            gradle test
      - store_test_results:
          path : build/test-results
  package:
    docker:   
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
            gradle jar
      - store_artifacts:
          path: build/libs
          destination: prefix
workflows:
  version: 2
  jobs:
      - test
      - package: 
        requires:
           - test

